apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-calendar-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/seokheounjo/teamproject.git
    targetRevision: master
    path: deploy/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

