apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
namePrefix: prod-
resources:
- ../../base
images:
- name: app
  newName: ghcr.io/seokheounjo/dev-calendar
  newTag: 51ac77cbbcc6287f310ad555a73cae0f3083fd3b
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
    name: dev-calendar
- patch: |-
    - op: replace
      path: /metadata/name
      value: prod
  target:
    kind: Namespace
    name: app
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: prod.dev-calendar.local
  target:
    kind: Ingress
    name: dev-calendar
